# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Permission:
  fields:
    default: role_id, user_id, user, role
    form: role_id, user_id, user, role
  order_by: 
  relationships: role, user
  filters: 
  search: 
  application: rails3

Role:
  fields:
    default: name
    form: name
  order_by: 
  relationships: permissions, users
  filters: 
  search: name
  application: rails3

User:
  fields:
    default: login, name, email, remember_token, remember_token_expires_at, activation_code, activated_at, enabled
    form: login, name, email, remember_token, remember_token_expires_at, activation_code, activated_at, password_reset_code, enabled
  order_by: 
  relationships: permissions, roles
  filters: 
  search: name
  application: rails3

