# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

User:
  fields:
    default: login, name, email, remember_token, remember_token_expires_at, activation_code, activated_at, enabled
    form: login, name, email, remember_token, remember_token_expires_at, activation_code, activated_at, password_reset_code, enabled
  order_by: 
  relationships: images, permissions, roles
  filters: 
  search: name
  application: rails3
